### PR TITLE
Fix #19, added i18n, setting suggestion

### LINKED ISSUE #19: Setting description missing
image

We should give user suggestion which settings are available and give them a description of each setting.

### PR DESCRIPTION
**Pull request by upupming**
### Improved settings

1. Added: i18n
2. Added: setting suggestion
3. Fixed: `Picgo-Core` changes the `settings.json` and makes it dirty
4. Improved: keep data types consistent with `Picgo-Core`

New settings UI:

The `picgo` object logged:

And the `picgo.picBed` Object logged:

Inspired by [Markdown All in One](https://github.com/yzhang-gh/vscode-markdown) and thanks to [Yu Zhang](https://github.com/yzhang-gh).

#### Suggested settings for `PicGo-electron` users

```json
{
    "picgo.configPath": "C:\\Users\\Doraeming\\AppData\\Roaming\\PicGo\\data.json",
    "picgo.logPath": "C:\\Users\\Doraeming\\AppData\\Roaming\\PicGo\\data.json"
}
```

In this way:

1. `vs-picgo` will use the same configuration as `PicGo-electron`.
2. `PicGo-electron` will got all uploaded images by `vs-picgo`.

#### Further working

Apply `i18n` to `ts` file, too. This can be implemented by something like [localize.ts](https://github.com/yzhang-gh/vscode-markdown/blob/master/src/localize.ts).

### CODE REVIEW

**Comment by upupming** [comment]
Once this PR is finished, I think we can continue working on #10, cheers!

**Comment by upupming** [comment]
> The only thing we should pay attention to is these changes should be compatible.

@Spades-S I think we can be more ambitious and completely abandon the old config style!

**Comment by Spades-S** [comment]
@upupming  Maybe you're right.

**Comment by Spades-S** [comment]
@upupming  This PR is a milestone! Great job.

**Pull request merged**
