### PR TITLE
Modify instruction text

### PR DESCRIPTION
**Pull request by Spades-S**
Modify instruction text

### CODE REVIEW

**Comment by upupming** [comment]
Just a note, we should update screenshot of configuration when publishing v2.0.0.

**Comment by upupming** [comment]
LGTM, I will modify the instruction a little.

**Comment by Spades-S** [comment]
> Just a note, we should update screenshot of configuration when publishing v2.0.0.

@upupming  Sure

**Comment by upupming** [comment]
Why are you closing this PR?
I'm committing and found the following error respect to `pre-hook`:

image
Fixed by https://github.com/line/line-bot-sdk-nodejs/issues/37#issuecomment-469590046

**Comment by upupming** [comment]
I have made some small changes, does it look good to you? Please feel free to request changes!

**Comment by Spades-S** [comment]
> Why are you closing this PR?
> I'm committing and found the following error respect to `pre-hook`:
> 
> image
> Fixed by [line/line-bot-sdk-nodejs#37 (comment)](https://github.com/line/line-bot-sdk-nodejs/issues/37#issuecomment-469590046)

@upupming  I'm updating the screenshot, and plan to reopen this on finishing

**Comment by upupming** [comment]
That would be nice, I think we can publish v2.0.0 on this PR finished!

**Pull request merged**
