### PR TITLE
feat: 🎸 add support for svg

### PR DESCRIPTION
**Pull request by kkyeer**
add support for svg image while choosing files

### CODE REVIEW

**Comment by upupming** [comment]
@kkyeer Have you checked all supported formats by picgo core?

**Comment by kkyeer** [comment]
> @kkyeer Have you checked all supported formats by picgo core?

According to Mozilla's [list](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types), there should be at least 5 types: .jfif, .pjpeg, .pjp, .avif, .apng, should I add them all or give users  an option to choose file freely?
Besides, I think whether a file type is supported is up to user's markdown renderer,am I right ?
@upupming

**Comment by upupming** [comment]
@kkyeer 
1. `.svg` is not supported by all uploaders, for example, SM.MS doesn't support `.svg` but tcyun does support `.svg`. I think we should report an error message to the user if they uploaded an image file with a type not supported by the current uploader. Could you please add this error message, too?
    
image

2. As for .jfif, .pjpeg, .pjp, .avif, .apng, I think it is not necessary to add them because we seldom use them.

**Comment by kkyeer** [comment]
1. There is  already a working message chain to display see error message returned by suppliers as showed below.But SM.MS's api server did not give a reasonable error message,nor there api docs.
图片
2. As VsCode do not support "all files" if given file suffix filters, it is currently  impossible to let user choose freely .
3. To achieve that，either override error message with unreliable manner in plugins( no accurate api doc)，or add a new feature for plugins to list support image types ,then extension can iterate over this list.
@upupming how do your sugguest to procceed?

**Comment by upupming** [comment]
@kkyeer Great point, here is my suggestion:
I think the best way is to let the uploader define all supported file types, but there is no such an API such as `picgo.getSupportedImageTypes` to get all supported file types by uploader. I think we can keep the hard-coded file types by now, and make a PR to PicGo-Core to add this API. After the next release of PicGo-Core, we can update our code to use the new API.

**Review by upupming — APPROVED** [review]

**Comment by upupming** [comment]
@Spades-S Did you have any comment on this, I think it looks good to me, can we merge it?

**Pull request merged**
