### PR TITLE
Added custom upload name & output format, fix #10

### LINKED ISSUE #10: 请问customUrl该如何设置？
似乎默认图片保留原有名字，我想请问除此之外可以加上别的内容吗？ 比如`${mdFileName}` ，`${fileName}` 以及 `${date}`。
我把 `customUrl` 设置成 `${fileName}_${dateTime}` 之类就失败了。

希望能给一个关于这个的教程， 非常感谢！

### PR DESCRIPTION
**Pull request by upupming**
### Custom upload name & output format

- Added: custom upload name & output format
- Added: show error message on picgo error and cancel the upload progress dialog.

Configuration screenshot:

#### better error message

Inspired by:

- [vscode-paste-image-to-qiniu](https://github.com/favers/vscode-qiniu-upload-image)
- [picgo-plugin-autocopy](https://github.com/PicGo/picgo-plugin-autocopy)

PS: I found another bug, when I uploaded several large images (for example, the two gif's above) using `smms` (on version 1.0.6 and until this PR), I always got the `socket hang up` error, I'm not sure if it is my network issue, but upload using browser is okay. This should be okay if user don't upload very large files. I think if may be a bug of `PicGo-Core`.

### CODE REVIEW

**Comment by upupming** [comment]
Only when I opened this PR did I realize that you are going to release v2.0.0, that's great!

**Comment by Spades-S** [comment]
smms  has a limit to image size,  2M

Li Yiming <notifications@github.com>于2019年4月6日 周六下午5:33写道：

**Comment by upupming** [comment]
Just a small suggestion, Current the picture is so large and people have to scroll heavily between sections.
We could limit the image height in the README or use `<details>` to collapse them to make it more readable, or we can add a TOC to README ([Markdown All in One](https://github.com/yzhang-gh/vscode-markdown) is good at this.)

**Comment by upupming** [comment]
> smms has a limit to image size, 2M 

image

Seems to be 5MB as per https://sm.ms/

**Comment by upupming** [comment]
@Spades-S I'm adding `appveyor`, so I will merge it first because this commit will fix this build error too:
```bash
> tsc -p ./

node_modules/picgo/dist/lib/Request.d.ts:2:21 - error TS7016: Could not find a declaration file for module 'request-promise-native'. 'C:/Users/Doraeming/vs-picgo/node_modules/request-promise-native/lib/rp.js' implicitly has an 'any' type.
  Try `npm install @types/request-promise-native` if it exists or add a new declaration (.d.ts) file containing `declare module 'request-promise-native';`

2 import request from 'request-promise-native';
                      ~~~~~~~~~~~~~~~~~~~~~~~~
```

**Pull request merged**
